### ISSUE TITLE
questionable test in WW

### ISSUE THREAD

**Issue by catfact** [tehn/aleph#253]
https://github.com/tehn/aleph/blob/dev/apps/bees/src/ops/op_ww.c#L994

`edit_cv_step` is unsigned, so that clause of the conditional will always fail.
not sure what it's supposed to catch, so heads up @tehn

**Comment by ghost** [comment]
ha - just discovered op_ww blows up if it's allocated memory isn't initialised to zero yikes!  (doesn't hard-crash bees but polling callback doesn't come up right so no visual grid feedback)

I guess that would be worth investigating at some point.

as a quick hacky fix I zero memory as first job in op_init:
https://github.com/rick-monster/aleph/commit/216fde29cf6709298c97f4e466ab15ea7a18458a

**Comment by ghost** [comment]
hmm also just a note to self - I made this commit:
https://github.com/rick-monster/aleph/commit/ce158e7ffa60843f428c5ef91327b881201a4f07
seems I thought it necessary for some reason to buffer op_ww outputs.  Might be a total red herring - IIRC I thought WW was buggy at some point because it's clock input requires both leading edge & trailing edge bangs...

**Comment by ngwese** [comment]
at first blush it seems reasonable. not sure why the the buffering would be needed.

if you want i can make an effort to test this change at some point this week.

**Comment by ghost** [comment]
hmm I'm really not sure about that commit, hence didn't put it into most recent pull request...

more generally, would actually like to see a couple of enhancements to op_ww:
- [x] figure out the issues with focus swapping: https://github.com/monome/aleph/issues/169
- [x] make the WW clock work with a single stream of metro bangs on clock in (rather than metro->toggle)
- [x] make WW pickle all it's state to scene (including percussion patterns)
- [ ] also possibly implement 'grid sharing' allowing host software grid to present as a local monome device & implement focus-switching over serial
