### ISSUE TITLE
debug via usb output

### ISSUE THREAD

**Issue by electropourlaction** [tehn/aleph#263]
I'm very puzzled by this, it's just that I can not get any readable debug messages anymore, older versions work fine, have just tried bees 0.7.1 again and I can't seem to get it to work, tried different baud rates.

can get it to work occasionally like this;
starting the app
connecting, with funky output
pulling the usb-cable
connecting again in a new terminal session

haven't found a workaround to get debug output during app_launch though

**Comment by ghost** [comment]
115200 is correct baud (though I guess if you see intermittent output you must be at correct baud).  Bees debug output is 90% working for me, though under certain conditions I do see the serial terminal fail to register as a device on my linux laptop (haven't exactly nailed this down yet).

/dev/ttyACM0 always comes back if I cycle the power on aleph twice.  The command I use to connect in order to see the boot cycle debug is minicom -b 115200 -D /dev/ttyACM0.  Once that program has connected once, the program stays open when cycling aleph power, enabling to see the boot messages.

What setup are you using to observe the bad intermittent behaviour? (OS, terminal program etc)

**Comment by ghost** [comment]
I can gather the debug output at app lauch if you link the code here (as I said, also keen to get the i2c working).  If I can get a bare i2c debug client working on icestick fpga then I can try to help with the aleph i2c thing (this looks like a good candidate http://www.fpga4fun.com/I2C_2.html)...

**Comment by electropourlaction** [comment]
using "screen /dev/tty.somemodem 57600" on OS X like I always have :)

happy to get help on the i2c!

**Comment by ghost** [comment]
not familiar with tty tools on OS X but the 57600 in that command looks to me like a baud rate (not the right one!).  IIRC the baud rate was changed from one release of bees to the next (some time ago)

Maybe this would be worth a shot?

screen /dev/tty.somemodem 115200

**Comment by tehn** [comment]
i'd suggest minicom (get it with homebrew)

brew install minicom

then

minicom -s

to set up the connection-- set your path and 115200

**Comment by ngwese** [comment]
Under OS X I use `sudo cu -l /dev/tty.usbmodemfd131 -s 115200` to connect to the debug output. The number at the end of the "usbmodem" device file changes from time to time....

**Comment by electropourlaction** [comment]
thanks for all the suggestions, still getting weird output, maybe it's something else, using the led to facilitate a simpler form of debug in the meantime! :)

**Comment by ghost** [comment]
might be worth trying a different usb cable if you have a spare... (kind of a long shot but I have seen weirdness with certain devices & bad usb cable)

**Comment by electropourlaction** [comment]
still weirdness, is there no one else that get's weird output?! it works about 1/5 of the times I try to connect which is even weirder!

**Comment by catfact** [comment]
not me... i did a bunch of serial stuff yesterday with 0.7.1... business as usual.

**Comment by electropourlaction** [comment]
good to hear, I'm gonna dig up my old macbook for a test, hoping this somehow happened with a higher OS X... going nuts here from unplugging this usb-cable :)

**Comment by electropourlaction** [comment]
installed ftdi drivers, I think that did it! (I'm on OS X 10.10)

http://www.ftdichip.com/Drivers/VCP.htm

**Comment by electropourlaction** [comment]
ah, it started again, the drivers did not help unfortunately...

**Comment by catfact** [comment]
since we're having trouble reproducing the problem, could you give us more details?
- are you using a build from the release pages? or building from source? if the latter, have you checked the baud settings in the board configuration file?
- are you loading a scene? what is it? if you have a scene with tons of stuff going on, it might simply not have time to transmit the debug messages.
- have you tried minicom as suggested? this program has the advantage of holding the port open when the aleph powers off, so you can powercycle and see the boot-up messages.

**Comment by electropourlaction** [comment]
I'm building from source, baud is now set to 115200

I'm debugging my prgm app, that's an interesting input but I also tested with bees and got the same problem unfortunately

I have tried minicom, but it did not do the trick

the scenario that is working best is when I'm connecting on the MODE-startup page, and connect before I start to reload a new version, then it usually works, otherwise I pull the cable and reconnect a couple of times until I get it to work

maybe it could be OS X related because I didn't have this problem before, now I'm on 10.10

edit: dug out my old macbook (OS X 10.6) for a test and it works so I guess it's related to OS X 10.10 or something is wrong with my current computer, closing this now (for real)!
